### PR TITLE
replace CRLF (windows) with LF (unix) line breaks

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by s0faking** [comment]
hey rechi. thanks for the changes. sorry i missed that one and already had quite some changes for the new timeshift livestream in place. mea culpa, i'm slow these days with the little one keeping me busy

**Comment by s0faking** [comment]
@Rechi one question tough about the addon. i've been thinking to merge the orfon code with the tvthek addon. do you know by chance if it would be a problem to change the name in the addon.xml when publishing it on the official repo. I think this might be for the best, but i couldn't find anything in the addon submission guidelines. if not can you point me to someone who can help me with that question maybe? the IRC channel is not active anymore, right?

**Comment by Rechi** [comment]
IMO I don't see a problem. The important thing is to have a higher version number, as the already submitted version.
https://github.com/basrieter (and https://github.com/enen92) are the ones reviewing the addon submissions.
The IRC channel is still active.

I would try to submit it and look at the reviewers opinion. With an n existing PR it is easier for me to contact the person, if the are any issues or questions.

**Comment by s0faking** [comment]
ok thanks for the hints. i will go for the PR

**Pull request closed without merging**
